### ISSUE TITLE
error while generating OpenAPI spec on operation: ID func1 is already used by another operation

### ISSUE THREAD

**Issue by FabienM** [wI2L/fizz#13]
In order to inject dependencies in my tonic handlers, i use some closure to declare them:

```go
func HandlerFindByPage(repository PageableRepository) gin.HandlerFunc {
	return tonic.Handler(func(c *gin.Context) (*PagedResources, error) {
...
        }, http.StatusPartialContent)
}

// HandlerRemoveAll removes a whole collection
func HandlerRemoveAll(repository TruncatableRepository) gin.HandlerFunc {
	return tonic.Handler(func(c *gin.Context) error {
		return repository.Truncate()
	}, http.StatusNoContent)
}
```

The associated fizz router group looks like:

```
	appRoutes := router.Group("/applications", "applications", "Applications management")
	appRoutes.GET("/", nil, hateoas.HandlerFindByPage(appRepo))
	appRoutes.DELETE("/", nil, hateoas.HandlerRemoveAll(appRepo))
```

In such a case, fizz panics at runtime with following error and trace:

```
panic: error while generating OpenAPI spec on operation DELETE /api/v1/applications/: ID func1 is already used by another operation

goroutine 1 [running]:
stash.ovh.net/urba/appcatalog/api/vendor/github.com/wI2L/fizz.(*RouterGroup).Handle(0xc4202b1ec0, 0xc4202d0c00, 0x15, 0x1a63c61, 0x6, 0x0, 0x0, 0x0, 0xc4202bc1f8, 0x1, ...)
	/Users/fmeurill/Workspaces/go/src/stash.ovh.net/urba/appcatalog/api/vendor/github.com/wI2L/fizz/fizz.go:196 +0xa43
stash.ovh.net/urba/appcatalog/api/vendor/github.com/wI2L/fizz.(*RouterGroup).DELETE(0xc4202b1ec0, 0x1a615e6, 0x1, 0x0, 0x0, 0x0, 0xc4202bc1f8, 0x1, 0x1, 0x0)
	/Users/fmeurill/Workspaces/go/src/stash.ovh.net/urba/appcatalog/api/vendor/github.com/wI2L/fizz/fizz.go:138 +0xb8
stash.ovh.net/urba/appcatalog/api/v1/routing.registerRoutes(0xc4202b1e60, 0xc4202bc1b8, 0xc4202bc1c0, 0xc4202bc1c8, 0xc4202b4850)
	/Users/fmeurill/Workspaces/go/src/stash.ovh.net/urba/appcatalog/api/v1/routing/routes.go:16 +0x27a
stash.ovh.net/urba/appcatalog/api/v1/routing.Init(0xc420306090, 0xc4202b1e60)
	/Users/fmeurill/Workspaces/go/src/stash.ovh.net/urba/appcatalog/api/v1/routing/routes.go:48 +0xb2
stash.ovh.net/urba/appcatalog/api/routing.NewRouter(0xc420306090, 0x1a62916, 0x5, 0x1a61f62, 0x4, 0xc4202be301, 0xc4202b83c0, 0x0)
	/Users/fmeurill/Workspaces/go/src/stash.ovh.net/urba/appcatalog/api/routing/routes.go:38 +0x55d
main.main()
	/Users/fmeurill/Workspaces/go/src/stash.ovh.net/urba/appcatalog/api/cmd/appcatalog/main.go:91 +0xa4d
```

**Comment by wI2L** [comment]
All operation IDs in the spec must be unique. Golang names all the closure the same way, so you must manually override using the `fizz.ID` operation option.

```go
appRoutes.GET("/", []fizz.OperationOption{
    fizz.ID("MyOperationID")
}, hateoas.HandlerFindByPage(appRepo))
```

I'll update the README to highlight this common case.
